[[resources]]
name = "sponza"
url = "https://github.com/acccoco/assets/releases/download/fbx/sponza_0.0.2.zip"
resource_type = "zip"
target_dir = "assets/fbx"
rename_to = "sponza"  # 可选：重命名解压后的顶级目录
force_download = false
