[package]
name = "truvis-resource"
version = "0.1.0"
edition = "2024"

[dependencies]
truvis-gfx = { workspace = true }

ash = { workspace = true }
slotmap = { workspace = true }
image = { workspace = true }
vk-mem = { workspace = true }
tracy-client = { workspace = true }
